name: tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v6
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum
    - name: Go Mod Tidy
      run: go mod tidy
    - name: Test
      run: go build -v && go test ./...
