name: tests

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}

env:
  GOWORK: off

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v6
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum
    - name: Go Mod Tidy
      run: go mod tidy
    - name: Check go.mod and go.sum
      run: git diff --exit-code -- go.mod go.sum
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test ./... -count=1
    - name: Vet
      run: go vet ./...
